### ISSUE TITLE
open-source.rackster.ch BTSync "Repo"

### ISSUE THREAD

**Issue by michelkaeser** [vrypan/btsync-keys#3]
Hi there.

Would you mind adding: https://open-source.rackster.ch/project/debian-7-0-openvz-templates/note/BTSync to your list?

Thx!

**Comment by vrypan** [comment]
Sure. Can you please provide me with the line to put in keys.txt?

**Comment by michelkaeser** [comment]
R63RB5DU6655XS6KF46V4R5TA4LE7AWAZ open-source.rackster.ch R

Thx
